title: Glykeria Spyrou
logo: /assets/img/circle_image.png
# description: text below image
# show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Custom CSS
# sass:
#   style: compressed

# defaults:
#   -
#     scope:
#       path: ""
#     values:
#       layout: default

# Add this to use your CSS
# include:
#   - assets/css/style.css